
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.21/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#    jackson的这个non_null 属性使得在json字符串中为null的字符串都不会显示
  jackson:
    default-property-inclusion: non_null
#    实际展示为URL的前缀
server:
  servlet:
    context-path:  /sell
