#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #    jackson的这个non_null 属性使得在json字符串中为null的字符串都不会显示
  jackson:
    default-property-inclusion: non_null
#    实际展示为URL的前缀
server:
  servlet:
    context-path:  /sell

wechat:
#  公众账号，授权
#  mpAppId: wxbe91ae8388f6a0f2
#  mpAppSecret: 8015383f0d10e9bde38f0e3952d37138

# 支付/商户号
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
#  商户密钥
  mchKey: C5245D70627C1F8E9964D494B0735025
#  发起支付不需要证书（keyPath），退款需要证书
  keyPath: ./static/h5.p12
#  URL接收微信的异步通知
  notifyUrl: http://sell35.natapp1.cc/sell/pay/notify

  #  微信登陆
  openAppId: wxd2352345
  openAppSecret: 2423483f0d10e9bde38f0e3952348